// "use client"
import Link from "next/link";
import style from "./post.module.css"

export const getPosts = async () =>{
  const res = await fetch('https://jsonplaceholder.typicode.com/posts')
  const data = await res.json();
  return data;
}

export const metadata = {
    title: "All Post",
    description: "Generated by create next app",
};

const page = async () => {
    const posts = await getPosts()
    return (
        <div>
            <h1>post page</h1>
            {/* <p>{JSON.stringify(posts)}</p>*/}

            <div  className="grid grid-cols-5 gap-5 p-4">
                {
                    posts.map((d) => {
                        return<>
                            <div key={d.id} className="border-yellow-400 border-2 px-10">
                                <p>{d.id}</p>
                                <p className={`${style["post-title"]}`}>{d.title}</p>
                                <p>{d.body}</p>
                                <Link href={`/post/${d.id}`}>details</Link>
                            </div>
                        </>
                    })
                }
            </div>

        </div>
    );
};

export default page;